// Generated by gmmproc 2.54.0 -- DO NOT MODIFY!
#ifndef _GIOMM_INITABLE_P_H
#define _GIOMM_INITABLE_P_H


#include <glibmm/private/interface_p.h>

#include <glibmm/private/interface_p.h>

namespace Gio
{

class Initable_Class : public Glib::Interface_Class
{
public:
  using CppObjectType = Initable;
  using BaseObjectType = GInitable;
  using BaseClassType = GInitableIface;
  using CppClassParent = Glib::Interface_Class;

  friend class Initable;

  const Glib::Interface_Class& init();

  static void iface_init_function(void* g_iface, void* iface_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.

  //Callbacks (virtual functions):
  static gboolean init_vfunc_callback(GInitable* self, GCancellable* cancellable, GError** error);
};


} // namespace Gio


#endif /* _GIOMM_INITABLE_P_H */

